### ISSUE TITLE
Environment: Terrain Features: Steel Deposits

### ISSUE THREAD

**Issue by SchwiftyK** [blacksmoke26/dawn-of-man-generator#1]
There are no "Steel-Deposits" in the game.

Have a look at madrugas builtin environments too ;-)
http://madrugaworks.com/dawnofman/files/BuiltinEnvironments.zip

**Comment by blacksmoke26** [comment]
Will do! Thanks!

**Comment by blacksmoke26** [comment]
Steel Deposite: Removed

Please see the commit:
[#8d329](https://github.com/blacksmoke26/dawn-of-man-generator/commit/8d329f845a263427e43644b7b4e5ef1cb676e424)

Thank You!
