### ISSUE TITLE
Enhance UI Layout, Simplify Overcomplexity, Implement Side-by-Side Functionality for elements and code section

### ISSUE THREAD

**Issue by zainbokhari96** [blacksmoke26/dawn-of-man-generator#10]
- Simplifying overcomplex UI elements and long remove vertical scroll.

- Implementing side-by-side functionality for elements and editor.

- These changes aim to improve user experience and streamline user experience.

**Comment by blacksmoke26** [comment]
Implemented:
Commit: https://github.com/blacksmoke26/dawn-of-man-generator/commit/980b3712bc95bae218df16c731d917c5d9aee82b

Changes are live. Thank you, Zain:
Here the release: https://github.com/blacksmoke26/dawn-of-man-generator/releases/tag/2.2
