### ISSUE TITLE
Tree spawn override

### ISSUE THREAD

**Issue by SchwiftyK** [blacksmoke26/dawn-of-man-generator#2]
Just to let you know. It is possible to override the "height values" where trees spawn in the environment file. I just don't use it (often). But it might be a nice addition to your Generator if you plan to polish it.

Code looks like this:

`		<tree_override_prototype>
			<id value="Spruce"/>
			<min_altitude value="0" />
			<max_altitude value="14"/>
		</tree_override_prototype>`

**Comment by blacksmoke26** [comment]
So I can add multiple lists of trees?

For example:

```xml
<tree_override_prototype>
  <id value="{string}"/>
  <min_altitude value="{integer}" />
  <max_altitude value="{integer}"/>
</tree_override_prototype>
```

Right? And what's the min/max values of:
`min_altitude` : >= 0
`max_altitude` : <= ?

**Comment by SchwiftyK** [comment]
The game spawns certain trees on certain altitudes of the terrain. Those altitudes can be overwritten. Here a picture (i hope it says more than 1000 words :-)): https://steamcommunity.com/profiles/76561198028674171/screenshot/802134454922108692

This is the example code:

	<?xml version="1.0" encoding="utf-8"?>
	<environment>
		<resource_factor value="10.5"/>
		<distance_height_offset value="0.015"/>
		<ford_distance_factor value="0.65"/>
		<sun_angle_factor value="0.0003"/>
		<trees_everywhere value="false"/>
	 	<trees values="Oak Fir Cherry"/>
		<tree_override_prototypes>

			<tree_override_prototype>
				<id value="Oak"/>
				<min_altitude value="5" />
				<max_altitude value="10"/>
			</tree_override_prototype>

			<tree_override_prototype>
				<id value="Fir"/>
				<min_altitude value="15" />
				<max_altitude value="80"/>
			</tree_override_prototype>

			<tree_override_prototype>
				<id value="Cherry"/>
				<min_altitude value="-5" />
				<max_altitude value="0"/>
			</tree_override_prototype>

		</tree_override_prototypes>


	</environment>

**Comment by blacksmoke26** [comment]
I assume that `min_altitude` and `min_altitude` should be;

`min_altitude` can be less than 0... (-100 to 100 but less than `max`)
`max_altitude` max value is 100...? (bigger than `min`)

Also, the tree id `VALUE` is unique in the list, (no more than one at same time)

If my theory is correct. I add a new generator 'Trees'

**Comment by blacksmoke26** [comment]
I assume that `min_altitude` and `min_altitude` should be;

`min_altitude` can be less than `0`... _(-100 to 100 but less than max)_
`max_altitude` max value is `100`...? _(bigger than `min`)_

Also, the tree id `value` is unique in the list. _(no more than one at the same time)_

If my theory is correct. I will start work on a new generator 'Trees'.

**Comment by blacksmoke26** [comment]
`<sun_angle_factor value="0.0003"/>`

Ah, now I see. The `sun_angle_factor` has 4 decimals... Will fix it too.

**Comment by SchwiftyK** [comment]
Yes, min_altitude should be "less or equal" max_altitude.
Both values can be less than 0 (-5 for example). As you maybe saw in the screenshot  the min value -5 places cherry tree inside the river (where they do not belong) it was just to demonstrate how that works. So, -100(maybe even -20) might spawn trees somewhere far beneath the ground, where nobody needs them. might even produce a crash.

the "tree_override_prototypes" is an optional part of the environment and is filled with default values from the game if not specified. like i said i mostly never use it, because i don't care where specific trees spawn. (could be used to make a oak tale and fir mountains) i use only trees_everywhere=false to prevent a "tree flodding of the map" that would kill my fps.

Resssource factor is ment as a multiplication factor. "10" would mean 10 times more ressources than usually (see amount of deposits and sticks/flint in the screenshot). 

sun_angle_factor can have mor than 4 decimals but is mostly not needed. it is the factor for the sun movement between the seasons. high values like "4", "-30" produce "something like more or less smooth sun movement between the seasons" a value like "36000(thirtysixthousand)" leads to a disco strobo light effect between seasons. The workshop Scenario "Unknown Frontier overhaul" uses the sun angle factor and high mountains to simulate something like day / night cycles.

Feel free to add me on Steam for some direct chat. 

Have you already made some nice environments for the game?? Would be glad to play / test / see them.

**Comment by blacksmoke26** [comment]
`Have you already made some nice environments for the game?? Would be glad to play / test / see them.`

Yeah, I have created a lot but few catch my eye. 

I will start implementation in the next few days!

Thank You!

**Comment by blacksmoke26** [comment]
@SchwiftyK I have implemented the **Tree Prototypes Editor**.

1. Please visit the page: https://dawn-of-man-mod-gen.netlify.com/
2. Environment > Trees (Terrain) > Override Tree Prototypes

**Comment by blacksmoke26** [comment]
@SchwiftyK Still around? I have started again on the generator. Would love to use your help. Let me know if we can connect.
